# Generated by Django 3.1.2 on 2020-10-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalgaryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('house_alpha', models.CharField(max_length=1)),
                ('street_quad', models.CharField(max_length=2)),
                ('street_name', models.CharField(max_length=16)),
                ('street_type', models.CharField(max_length=2)),
            ],
        ),
    ]
