# Generated by Django 3.1.2 on 2020-10-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='core.calgaryaddress')),
            ],
        ),
    ]
