# Generated by Django 3.1.2 on 2020-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='address_string',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
