# Generated by Django 3.1.2 on 2020-10-15 13:37

from django.db import migrations
import download.validators


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_pdf_address_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='upload_file',
            field=download.validators.RestrictedFileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
