# Generated by Django 3.1.2 on 2020-10-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20201015_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='address',
        ),
    ]
