# Generated by Django 3.1.2 on 2020-10-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_remove_pdf_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='address_string',
            field=models.CharField(max_length=128),
        ),
    ]
