# Generated by Django 3.1.2 on 2020-10-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_auto_20201024_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='address_string',
        ),
        migrations.AddField(
            model_name='pdf',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='download.address'),
            preserve_default=False,
        ),
    ]
