# Generated by Django 3.1.2 on 2020-10-24 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_auto_20201024_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
