# Generated by Django 3.1.2 on 2020-11-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quoteuser'),
        ('download', '0007_pdf_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='valid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ref_code', models.CharField(max_length=8)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quoteuser')),
            ],
        ),
    ]
