# Generated by Django 3.1.2 on 2020-11-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quoteuser'),
        ('download', '0009_auto_20201106_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='download.pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.quoteuser')),
            ],
        ),
    ]
