# Generated by Django 3.1.2 on 2020-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0011_downloadattempt_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadattempt',
            name='successful',
        ),
        migrations.AddField(
            model_name='downloadattempt',
            name='code_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadattempt',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
